debug: false

# If this is true ALL the built-in implementations for each mod will be ignored
# Meaning that the hook AND allowed config from below will not do anything
purely-api: false

# patches
patches:
  potion-effect-kick-patch:
    enabled: true

# Mod Settings
mods:
  off-hand:
    allowed: true # If true: the mod is forcibly disabled while the player is connected
    hook: true # If true: the hook will be handled by this plugin, if false: you will need to handle the hook
  totem-tweaks:
    allowed: true
    hook: true
  free-look:
    allowed: false
  tps-mod:
    allowed: true
    hook: true
  anchor-renderer:
    allowed: true
    hook: true